// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: packet_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Packet {

  /// <summary>Holder for reflection information generated from packet_type.proto</summary>
  public static partial class PacketTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for packet_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFwYWNrZXRfdHlwZS5wcm90bxIGcGFja2V0KoQECgRUeXBlEggKBE5PTkUQ",
            "ABILCgdDT05ORUNUEAISDgoKRElTQ09OTkVDVBADEg0KCUVSUk9SX0FDSxAE",
            "Eg0KCUxPR0lOX1JFURBkEg0KCUxPR0lOX0FDSxBlEhYKEkVOVEVSX05FV19V",
            "U0VSX1JFURBmEhYKEkVOVEVSX05FV19VU0VSX0FDSxBnEgwKCE1PVkVfUkVR",
            "EGkSDAoITU9WRV9BQ0sQahISCg5FTlRFUl9ST09NX1JFURBrEhIKDkVOVEVS",
            "X1JPT01fQUNLEGwSFQoRR0VUX1JPT01fTElTVF9SRVEQbRIVChFHRVRfUk9P",
            "TV9MSVNUX0FDSxBuEhEKDU1BS0VfUk9PTV9SRVEQbxIRCg1NQUtFX1JPT01f",
            "QUNLEHASFgoSTU9WRV9ST09NX1VTRVJfUkVREHESFgoSTU9WRV9ST09NX1VT",
            "RVJfQUNLEHISFgoSRVhJVF9ST09NX1VTRVJfUkVREHMSFgoSRVhJVF9ST09N",
            "X1VTRVJfQUNLEHQSGwoXRU5URVJfTkVXX1JPT01fVVNFUl9SRVEQdRIbChdF",
            "TlRFUl9ORVdfUk9PTV9VU0VSX0FDSxB2Eg4KCkxPR09VVF9SRVEQdxIOCgpM",
            "T0dPVVRfQUNLEHgSEgoOQ0FTVF9TS0lMTF9SRVEQeRISCg5DQVNUX1NLSUxM",
            "X0FDSxB6YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Packet.Type), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Type {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("CONNECT")] Connect = 2,
    [pbr::OriginalName("DISCONNECT")] Disconnect = 3,
    [pbr::OriginalName("ERROR_ACK")] ErrorAck = 4,
    [pbr::OriginalName("LOGIN_REQ")] LoginReq = 100,
    [pbr::OriginalName("LOGIN_ACK")] LoginAck = 101,
    [pbr::OriginalName("ENTER_NEW_USER_REQ")] EnterNewUserReq = 102,
    [pbr::OriginalName("ENTER_NEW_USER_ACK")] EnterNewUserAck = 103,
    [pbr::OriginalName("MOVE_REQ")] MoveReq = 105,
    [pbr::OriginalName("MOVE_ACK")] MoveAck = 106,
    [pbr::OriginalName("ENTER_ROOM_REQ")] EnterRoomReq = 107,
    [pbr::OriginalName("ENTER_ROOM_ACK")] EnterRoomAck = 108,
    [pbr::OriginalName("GET_ROOM_LIST_REQ")] GetRoomListReq = 109,
    [pbr::OriginalName("GET_ROOM_LIST_ACK")] GetRoomListAck = 110,
    [pbr::OriginalName("MAKE_ROOM_REQ")] MakeRoomReq = 111,
    [pbr::OriginalName("MAKE_ROOM_ACK")] MakeRoomAck = 112,
    [pbr::OriginalName("MOVE_ROOM_USER_REQ")] MoveRoomUserReq = 113,
    [pbr::OriginalName("MOVE_ROOM_USER_ACK")] MoveRoomUserAck = 114,
    [pbr::OriginalName("EXIT_ROOM_USER_REQ")] ExitRoomUserReq = 115,
    [pbr::OriginalName("EXIT_ROOM_USER_ACK")] ExitRoomUserAck = 116,
    [pbr::OriginalName("ENTER_NEW_ROOM_USER_REQ")] EnterNewRoomUserReq = 117,
    [pbr::OriginalName("ENTER_NEW_ROOM_USER_ACK")] EnterNewRoomUserAck = 118,
    [pbr::OriginalName("LOGOUT_REQ")] LogoutReq = 119,
    [pbr::OriginalName("LOGOUT_ACK")] LogoutAck = 120,
    [pbr::OriginalName("CAST_SKILL_REQ")] CastSkillReq = 121,
    [pbr::OriginalName("CAST_SKILL_ACK")] CastSkillAck = 122,
  }

  #endregion

}

#endregion Designer generated code
